apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3 #Executa ate obter sucesso
  parallelism: 3 #Default um por vez
  template:
    spec:
      containers:
      - name: math-add
        image: ubuntu
        command: ['expr', '3', '+', '2']
      restartPolicy: Never
