apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  persistentVolumeReclaimPolicy: Retain #Recycle, Delete
  accessModes:
  - ReadWriteOnce #ReadOnlyMany #ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
