#Blue Green Strategy
# Alterna entre dois ambientes: um ativo e outro novo 
# Ao validar o novo, o tráfego é redirecionado.


#BLUE
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      version: v1
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v1
    spec:
      containers:
      - name: app-container
        image: myapp-image:1.0
  replicas: 5

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    version: v1

#GREEN
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-green
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      version: v2
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v2
    spec:
      containers:
      - name: app-container
        image: myapp-image:2.0
  replicas: 5
#update service to v2 after tests
#manually
