#Canary Strategy
#A estratégia canary libera uma nova versão para um pequeno grupo de usuários. 
#Se for estável, a atualização é gradualmente expandida até atingir todos.


#O servico distribui igualmente neste exemplo 83% para primary e 17% para canary
#Se quisessemos direcionar apenas 1% do trafego para o canary com essa estrategia precisariamos de 100 pods no primary
#Importante usar alguns servico mesh para essa estrategia

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-primary
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 5
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v1
        app: front-end
    spec:
      containers:
      - name: app-container
        image: myapp-image:1.0

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: front-end


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-canary
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      name: myapp-pod
      labels:
        version: v2
        app: front-end
    spec:
      containers:
      - name: app-container
        image: myapp-image:1.0
