apiVersion: v1
kind: ReplicaSet
metadata:
  name: simple-webapp
  labels: #essa label e para o replicaset necessario qndo outros objetos precisam descobri-la
    app: App1
    function: Front-end
  annotations: #Usado para guardar outras informacoes adicionais
    builVersion: "1.34"
spec:
  replicas: 3
  selector:
    matchLabels: # esta e a label q o replicaset procura
      app: App1
  template:
    metadata:
      labels:
        app: App1
        function: Front-end
    spec:
      containers:
      - name: simple-webapp
        image: simple-webapp


