apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: App1 #Label usada para buscar por pod com mesma label
  ports:
  - port: 80
    targetPort: 9376
    protocol: TCP
