# this type of secret never expire
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname

  annotations:
    kubernetes.io/service-account-token.name: dashboard-sa
