apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    env: production
spec:
  containers:
  - name: nginx
    image: nginx
#kubectl replace -f simple-webapp-2.yaml --force
#kubectl logs -f <pod-name> <continer-name-if-mult-pod>
