apiVersion: v1
kind: Pod
metadata:
  name: web-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ['sleep', '3600']
    securityContext:
      runAsUser: 100
      capabilities:
        add: ["MAC_ADMIN"]
