apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: bXlZcWw # echo -n 'mysql' | base64
  DB_User: cm9vDA== # echo -n 'root' | base64
  DB_Password: cGFzd3Jk # echo -n 'passwrd' | base64
